site_name: Sample API Docs
site_url: https://sumanlatamalik.github.io/sample-api-docs/
docs_dir: docs
site_dir: site
theme:
  name: material
nav:
  - Home: index.md
  - API Endpoints:
      - Overview: endpoints/index.md
      - Users: endpoints/users.md
  - Setup Guide: setup/index.md
  - Testing: testing/index.md
  - Deployment: deployment/index.md